export interface User {
    role: string,
    userName:string ,
    email:string,
    password:string,
    firstName:string,
    lastName:string,
    age:number,
    birthDay:Date,
    country:string,
    city:string,
    phoneNumber:string,
    about:string,
    job:string,
    imageUrl:string,
    language:string,
    gender:string,
    websiteUrl:string,
    githubUrl:string,
    linkedInUrl:string,
    socialMediaUrl:string,
    lastLogin:Date,
}
